### ISSUE TITLE
Wrong statement in the configuration doc page

### ISSUE THREAD

**Issue by jfradj** [odan/slim4-skeleton#105]
Hello,

`https://odan.github.io/slim4-skeleton/configuration.html` states that:

> The configuration files are loaded in this order:
> 
> Load default settings from: config/defaults.php
> 
> If the environment variable APP_ENV is defined, load the environment specific file, e.g. config/local.{env}.php
> 
> Load secret credentials (if file exists) from:
>- config/env.php
>- config/../../env.php

Which is not correct.
The PHP `glob()` function used, returns file paths alphabetically ordered, thus the secret credentials file (`env.php`) will be loaded BEFORE the environment specific file (`local.{env}.php`)

I think the issue isn't really in the documentation page, since it's the expected behavior.
The issue is in the `config/settings.php` file using the glob function thus loosing any kind of control on the load ordering

Regards,
Johann

**Comment by jfradj** [comment]
The following code replacement will fix the issue.

```
// Overwrite default settings with environment specific local settings
$configFiles = [
    __DIR__ . "/local.{$_ENV['APP_ENV']}.php",
    __DIR__ . '/env.php',
    __DIR__ . '/../../env.php',
];

foreach ($configFiles as $configFile) {
    if (!file_exists($configFile)) {
        continue;
    }

    $local = require $configFile;
    if (is_callable($local)) {
        $settings = $local($settings);
    }
}
```

**Comment by odan** [comment]
Thanks for the feedback. Your approach looks good. I will check it.

**Comment by odan** [comment]
Close this as fixed.
