### ISSUE TITLE
Missing TemplateRenderer/HtmlRenderer

### ISSUE THREAD

**Issue by gRegorLove** [odan/slim4-skeleton#114]
The [documentation](https://odan.github.io/slim4-skeleton/renderers.html) refers to `TemplateRenderer` (or `HtmlRenderer` in the code snippet), but TemplateRenderer looks like it was removed in [this commit](https://github.com/odan/slim4-skeleton/commit/dda1d9c1b74a1dbb89c5698cc39f583c57948571).

Is there a newer, preferred method for default HTML rendering with the skeleton, or is it meant for devs to implement as needed?

**Comment by odan** [comment]
Thanks for reporting. The documentation was not updated accordingly. The section in the docs has just been removed.

The `TemplateRenderer` has been removed to make this skeleton project more agnostic / universal, as an API usually does not need an HTML template engine. 

> Is there a newer, preferred method for default HTML rendering with the skeleton, or is it meant for devs to implement as needed?

This style / method is still the preferred recommend way for HTML rendering, but you need to add it to your project if needed.
For example, when you want to provide a Swagger documentation, or you want to build a frontend based on this skeleton, the `TemplateRenderer` would be still the recommended way.

**Comment by odan** [comment]
I'm closing this as "resolved."
