### ISSUE TITLE
Question: MVC vs ADR Pattern

### ISSUE THREAD

**Issue by borgogelli** [odan/slim4-skeleton#118]
Hi everyone,
I have to convert an old Controller class which has 20 methods which are associated to 20 routes, to the ADR pattern.
Should I have to write 20 Action classes or there is an more concise alternative solution ?

Regards from Italy

**Comment by odan** [comment]
> Should I have to write 20 Action classes

Hi! This approach might result in a larger number of classes, but by organizing your code this way, you can achieve a more modular and maintainable structure, which is one of the goals of the ADR pattern.

**Comment by borgogelli** [comment]
Thank you a lot
