### ISSUE TITLE
Markdown_to_Html Email implementation

### ISSUE THREAD

**Issue by fvtorres** [odan/slim4-skeleton#12]
Hello @odan,

I have an Issue implementing Markdown_to_Html Email extension

I have used this tutorial: https://twig.symfony.com/doc/3.x/filters/html_to_markdown.html that I will paste the code suggested below:

> Then, use the twig/extra-bundle on Symfony projects or add the extension explicitly on the Twig environment:

use Twig\Extra\Markdown\MarkdownExtension;

$twig = new \Twig\Environment(...);
$twig->addExtension(new MarkdownExtension());

> If you are not using Symfony, you must also register the extension runtime:

use Twig\Extra\Markdown\DefaultMarkdown;
use Twig\Extra\Markdown\MarkdownRuntime;
use Twig\RuntimeLoader\RuntimeLoaderInterface;

$twig->addRuntimeLoader(new class implements RuntimeLoaderInterface {
    public function load($class) {
        if (MarkdownRuntime::class === $class) {
            return new MarkdownRuntime(new DefaultMarkdown());
        }
    }
});

I added the extension in container.php, but wasn't sure if there is the place to add the RuntimeLoader, or if it is really necessary or a different approach is needed.

As far as I can tell it is being executed, but nothing changes the resulting email.

By the way, Im using the league/commonmark library as recommended here (https://symfony.com/doc/current/mailer.html#rendering-markdown-content)

Sorry to bother you with that

**Comment by odan** [comment]
I have tried it according to the documentation and it works like expected.

My steps:

```
composer require twig/markdown-extra
composer require twig/markdown-extra league/commonmark
```

Add the Twig extension in container.php for the `Twig::class` definition:

```php

use Twig\Extra\Markdown\DefaultMarkdown;
use Twig\Extra\Markdown\MarkdownExtension;
use Twig\Extra\Markdown\MarkdownRuntime;
use Twig\RuntimeLoader\RuntimeLoaderInterface;
// ...

Twig::class => function (ContainerInterface $container) {

    // ...
    $twig->addExtension(new MarkdownExtension());
    // ...

    $twig->addRuntimeLoader(new class implements RuntimeLoaderInterface {
        public function load($class) {
            if ($class === MarkdownRuntime::class) {
                return new MarkdownRuntime(new DefaultMarkdown());
            }
        }
    });
    // ...
}, 
```

Create a Twig template:

```twig
{% apply markdown_to_html %}

# Header

Text

## Top 1

{% endapply %}
```

Render it as usual:

```php
return $this->twig->render($response, 'filenametwig', $viewData);
```

Result:

![image](https://user-images.githubusercontent.com/781074/81014801-d2ebe880-8e5d-11ea-899e-6be891fbf01f.png)

![image](https://user-images.githubusercontent.com/781074/81014816-db442380-8e5d-11ea-90c0-2592b8cce599.png)

**Comment by fvtorres** [comment]
Hello @odan ,

Thanks for checking on this. I used your template and it worked here.

The issue was that I was using Markdown and Inky inside the same tags, and it was conflicting with each other.

This is the code I was using, and if you test there you wont get the H1

{% apply markdown_to_html|inline_css|inky_to_html %}
<style>
    h1 {
        color: #333;
    }
</style>
<container>
<row class="header">
<columns>
# Hello World
</columns>
</row>
</container>
{% endapply %}`



The solution  I found after knowing it was working (thanks for that!!), is to separate the tags, like this:

{% apply inline_css|inky_to_html %}
<style>
    h1 {
        color: #333;
    }
</style>
<container>
<row class="header">
{% apply markdown_to_html %}
# Hello World
{% endapply %}`
<columns>
</columns>
</row>
</container>
{% endapply %}`

I`m not sure if its the best solution, but it definitely works

Thanks again for your help!!
