### ISSUE TITLE
Link in docs is wrong

### ISSUE THREAD

**Issue by garciaantonio20k** [odan/slim4-skeleton#121]
In https://odan.github.io/slim4-skeleton/database.html
you link the word "repository" to https://designpatternsphp.readthedocs.io/en/latest/More/Repository/README.html
but now is not correct.
The correct "now" is https://designpatternsphp.readthedocs.io/More/Repository/README.html

**Comment by odan** [comment]
Thanks for reporting. It's fixed now.
