### ISSUE TITLE
logger test's settings are useless

### ISSUE THREAD

**Issue by jfradj** [odan/slim4-skeleton#122]
In the LoggerTestTrait.php class, you're not getting the settings from the container, you're defining by hand the settings for the logger making the settings files in the config folder useless (for configuring the logger).

**Comment by odan** [comment]
This is on purpose, because this is a (integration) test environment where I don't want to use that configuration from the application. The test only "configures" a "TestHandler" that allows you to assert for specific logger events.

**Comment by jfradj** [comment]
Makes sense and that what I thought.
Thus the local.test.php should not configure the logger.
I mean I was playing with those settings without seeing any impact because it was overridden ^^

**Comment by odan** [comment]
It is removed now. Thanks for reporting.

**Comment by odan** [comment]
I had to revert the change, because it is used within the Test-Environment (phpunit) for all loggers.
