### ISSUE TITLE
Using skeleton in a subdirectory

### ISSUE THREAD

**Issue by x821938** [odan/slim4-skeleton#126]
How would you adjust the .htaccess to make the skeleton work in a subdirectory?
I am writing an API wich resides in /var/www/api
It should be accessed by going to https://www.example.com/api

**Comment by odan** [comment]
In this case the Slim basePath must be set to `/api`.

```php
$app->setBasePath('/api');
```

**Comment by x821938** [comment]
Thanks a lot :) Now everything is working.
