### ISSUE TITLE
new project

### ISSUE THREAD

**Issue by blondie63** [odan/slim4-skeleton#13]
Hi, thanks for you job..
I'd like to start my project form your job but i don't understand if i've to start from this skeleton or from tutorial..

Thanks for help

ps. Have time to help me for pay ?

**Comment by odan** [comment]
Hi @blondie63 

For learning purpose I would start to read and try the [Slim 4 tutorial](https://odan.github.io/2019/11/05/slim4-tutorial.html) first. 

This skeleton project is based on the same Slim tutorial.

When you are done, you could download and use this skeleton for your project.

> Have time to help me for pay ?

I send you an email.
