### ISSUE TITLE
Cannot install csfr without using downgrade 

### ISSUE THREAD

**Issue by matejik** [odan/slim4-skeleton#130]
Hi, following the instructions I tried to install csrf(composer require slim/csrf) with the error below.  Downgrade required again

  Problem 1
    - Root composer.json requires slim/csrf ^1.4 -> satisfiable by slim/csrf[1.4.0].
    - slim/csrf 1.4.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require slim/csrf:*" to figure out if any version is installable, or "composer require slim/csrf:^2.1" if you know which you need.

**Comment by odan** [comment]
The latest version of the slim/csrf package supports only psr/http-message v1.0.

https://github.com/slimphp/Slim-Csrf/blob/1.4.0/composer.json#L21

I will try to create a PR to fix that.

**Comment by odan** [comment]
It should work now. Please try it again using the latest version.

https://github.com/slimphp/Slim-Csrf/releases/tag/1.5.0
