### ISSUE TITLE
I have some problem with UserAuth dependency on Class LoginSubmitAction

### ISSUE THREAD

**Issue by rafaelbozzetti** [odan/slim4-skeleton#16]
When I try to receive UserAuth dependency on LoginSubmitAction  class constructor, returns error "DI\Definition\Exception\InvalidDefinition". It's like as the class is not injected as dependency 

`    
public function __construct(Responder $responder, Session $session, **UserAuth $auth**)
    {
        $this->responder = $responder;
        $this->session = $session;        
        $this->auth = $auth;
    }
`
Any idea? Thank's

**Comment by odan** [comment]
Hi @rafaelbozzetti 

This can happen when the constructor contains a scalar value.

Maybe phpstan will show you whats missing. 
Try to run phpstan with `composer phpstan`. 
You can also try to run the tests with `composer test`

Then you should see / know more where is something wrong.

**Comment by rafaelbozzetti** [comment]
@odan Thanks a lot man! phpstan help me so much!! My mistake is on a specicic namespace in a class.  Sorry my lack!
