### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by carlosnarro** [odan/slim4-skeleton#17]
Hi @odan,

I need to change the default language. I have created my new language and if I assign the new language to the user, it works correctly with de logged user. But if I go to _config > defaults.php_ and modify the language in the parameter _'locale'_ with _'de_DE'_ or my new language, the language on the home page remains in English. 

Should I do something else?

Thanks

**Comment by odan** [comment]
The default locale in [config/defaults.php](https://github.com/odan/slim4-skeleton/blob/master/config/defaults.php#L72) is `en_US`.

If the user is not logged in the [TranslatorMiddleware](https://github.com/odan/slim4-skeleton/blob/master/src/Middleware/TranslatorMiddleware.php#L64) uses also `en_US` as fallback resp. default locale.

If the user is logged-in and has a locale (defined in the database field: users.locale) then the TranslatorMiddleware will switch to that specific local of the user.

**Comment by carlosnarro** [comment]
Ok! thanks a lot :D
