### ISSUE TITLE
vue.js integration

### ISSUE THREAD

**Issue by huseyinyildirimcom** [odan/slim4-skeleton#19]
Thank you for this application. I want to add vue.js to this application. How can I do it?

**Comment by odan** [comment]
I would recommend using [NPM and wepback](https://vuejs.org/v2/guide/installation.html#NPM).

Install Vue

```
npm install vue
```
Install Vue loader

```
npm install -D vue-loader vue-template-compiler
```

Add this webpack configuration to `webpack.config.js`:

https://vue-loader.vuejs.org/guide/#manual-setup

```js
// webpack.config.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  module: {
    rules: [
      // ... other rules
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      }
    ]
  },
  plugins: [
    // make sure to include the plugin!
    new VueLoaderPlugin()
  ]
}
```

Add this `vue` alias in `webpack.config.js`:

```
resolve: {
    alias: {
        vue: argv.mode === 'production' ? 'vue/dist/vue.min.js' : 'vue/dist/vue.js'
    }
},
```

Require `vue` in `layout/layout.js`:

```js
global.Vue = require('vue');
```

Create a new vue file, e.g.  `templates/home/home.vue`

```js
<script>
    var app = new Vue({
        el: '#app',
        data: {
            message: 'Hello Vue!'
        }
    })
</script>
```

Require the vue file in `home.js`

```js
require('./home.vue');
```

Add some html to the template:

```html
<div id="app">
    <h1>{{ message }}</h1>
</div>
```

Please note: Vue and Twig use the same template syntax `{{ }}`. Twig will parse this templates before Vue can render it in the browser.

**Comment by huseyinyildirimcom** [comment]
Thank you @odan.

I successfully did the integration :)
