### ISSUE TITLE
Add twig-translation dependency

### ISSUE THREAD

**Issue by killua-eu** [odan/slim4-skeleton#2]
Now that the twig-assets are there , would you mind adding twig-translation too? I think it would be a good addition.

**Comment by odan** [comment]
The package [odan/twig-translation](https://github.com/odan/twig-translation#slim-4-integration) is part of this Slim 4  skeleton now. I also created a new section in the readme to explain the [Slim 4 integration](https://github.com/odan/twig-translation#slim-4-integration). For more details you could take a look into the latest master.

To parse the Twig templates you could just [Poedit PRO](https://poedit.net/pro) or 
you [compile the Twig templates to PHP](https://github.com/odan/slim4-skeleton/blob/master/bin/parse-twig.php) and parse the PHP templates with the free version of [Poedit](https://poedit.net/).

Usage:
```
php bin/parse-twig.php
```

**Comment by carlosnarro** [comment]
You need add the sources paths "templates" on de_DE_messages.po file for update from code if you use Poedit PRO. You can open file with Poedit PRO

 > Catalogue > Properties... > Source paths > + 

and select the tempaltes path. Accept and click in "Update from code" and your twig strings translations appear for be translated.
