### ISSUE TITLE
Safari cannot open the page

### ISSUE THREAD

**Issue by ybelenko** [odan/slim4-skeleton#23]
Cannot send request via Guzzle in home controller.
It's weird, but when I add line `var_dump($learners);` I can see rendered response.
Without `var_dump` page doesn't renders at all.
```console
< HTTP/1.1 200 OK
< Date: Wed, 02 Sep 2020 10:53:40 GMT
< Server: Apache/2.4.34 (Unix) PHP/7.4.6
< X-Powered-By: PHP/7.4.6
< Cache-Control: max-age=0, private, must-revalidate
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8


* Received 1783 B chunk
* Illegal or missing hexadecimal sequence in chunked-encoding
* stopped the pause stream!
* Closing connection 20
```

```php
<?php

namespace App\Action\Home;

use App\Responder\Responder;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use GuzzleHttp\Client;

/**
 * Action.
 */
final class HomeAction
{
    /**
     * @var Responder
     */
    private $responder;

    /**
     * The constructor.
     *
     * @param Responder $responder The responder
     */
    public function __construct(Responder $responder)
    {
        $this->responder = $responder;
    }

    /**
     * Action.
     *
     * @param ServerRequestInterface $request The request
     * @param ResponseInterface $response The response
     *
     * @return ResponseInterface The response
     */
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $client = new Client();
        $learnersUrl = 'http://apitest.test/api/learners';// localhost
        $response = $client->request('GET', $learnersUrl);
        $learners = json_decode((string) $response->getBody(), true);
        // var_dump($learners);
        return $this->responder->render($response, 'home/home.twig', [
            'now' => date('d.m.Y H:i:s'),
        ]);
    }
}

**Comment by odan** [comment]
The `render` method is for rendering (twig) templates only. The Responder class also provicdes as `json` method the render json data. Also note that you should passs the data you want to render. Here is an example:

```php
$client = new Client();
$learnersUrl = 'http://apitest.test/api/learners';
$response = $client->request('GET', $learnersUrl);
$learners = json_decode((string) $response->getBody(), true);

return $this->responder->json($response, $learners);
```

**Comment by ybelenko** [comment]
That's what I thought about `render` method. What if I want to grab data with Guzzle and pass it down to Twig template in variable? I need to retrieve data before render, not after with JQuery Ajax or something.

**Comment by odan** [comment]
Then just pass the data to the `render` method in the second parameter.

```php
$client = new Client();
$learnersUrl = 'http://apitest.test/api/learners';
$response = $client->request('GET', $learnersUrl);
$learners = (array)json_decode((string) $response->getBody(), true);

return $this->responder->render($response, 'home/home.twig', $learners);
```

Is this what you are looking for?

**Comment by ybelenko** [comment]
Yeah, it doesn't work. Anyway, I think it somehow related to my local Apache server.
I define page like:
```php
// Define app routes

use App\Middleware\UserAuthMiddleware;
use Slim\App;
use Slim\Routing\RouteCollectorProxy;

return function (App $app) {
    // learners page
    $app->get('/learners', \App\Action\Learners\LearnersAction::class)->setName('learners');
};
```
Then I open Safari browser with `http://apitest.test/learners` and it says ''Safari can’t open the page “‎apitest.test/learners” because the server unexpectedly dropped the connection. This sometimes occurs when the server is busy. Wait for a few minutes and then try again." Seems like my own fault, but when I change url to `http://apitest.test/learners?query=test` it suddenly works like charm... Cannot understand what is wrong with my server config.

**Comment by odan** [comment]
Yes, this sounds like a local setup issue.

**Comment by ybelenko** [comment]
I've removed Guzzle request already, so it crashes by unknown reason. What is even more weird I figured out that it's Apple Safari only issue... Endpoint works correctly in Google Chrome and Desktop Insomnia App.

**Comment by odan** [comment]
```
< Transfer-Encoding: chunked
```

Looks like you are sending a junked response and Apple Safari has an issue with it. But this is not the default behavior of Slim or the Skeleton. It must be the webserver or another middleware. Do you use Apache with PHP-FPM? 
https://www.jeffgeerling.com/blog/2017/apache-fastcgi-proxyfcgi-and-empty-post-bodies-chunked-transfer

Try to disable the junked response and it should work.

**Comment by ybelenko** [comment]
🤦 🤦 🤦 

> ```php
> $response = $client->request('GET', $learnersUrl);`
>
> return $this->responder->json($response, $learners);
> ```

I was assigning Guzzle client output into `$response` argument by mistake and then passed it to responder.

**Comment by ybelenko** [comment]
> Try to disable the junked response and it should work.

I didn't found how to disable chunked response, but I found this `.htaccess` rule at stackoverflow:
```
SetEnvIfNoCase Request_URI get_file\.php$ no-gzip dont-vary
```

I don't know why, but it helps with my local Apache. If I remove this line my application breaks immediately. Sometimes it doesn't load page at all, sometimes it cannot load some .css file.
