### ISSUE TITLE
Integrate PHP-DI Slim Bridge to inject named path parameters

### ISSUE THREAD

**Issue by ybelenko** [odan/slim4-skeleton#30]
Accordingly to [PHP DI - Route placeholder injection](https://php-di.org/doc/frameworks/slim.html#route-placeholder-injection) it's possible to inject path parameters to controllers.

However it doesn't work with your boilerplate:
In `src/Action/Hello/HelloAction.php`:
```php
public function __invoke(
    $name,
    ServerRequestInterface $request,
    ResponseInterface $response
): ResponseInterface {
    $response->getBody()->write("Hello, $name");

    return $response;
}
```
got error:
```console
500 Internal Server Error - Error details: [0] Argument 2 passed to App\Action\Hello\HelloAction::__invoke() must implement interface Psr\Http\Message\ServerRequestInterface, instance of Slim\Psr7\Response given, called in /Users/ybelenko/Sites/ca_front_slim/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php on line 43
```

**Comment by odan** [comment]
Hi @ybelenko Yes, because this works only with the [PHP-DI bridge for Slim](https://php-di.org/doc/frameworks/slim.html#setup). 

To get the route placeholder you can already use the 3. `$args` parameter (without any additional dependencies).

```php
public function __invoke(
    ServerRequestInterface $request,
    ResponseInterface $response,
    array $args = []
): ResponseInterface {
    // Get route argument
    $name = (string)$args['name'];

    return $response;
}
```

**Comment by ybelenko** [comment]
@odan I know how to use `$args`. But it doesn't feel cool :smile:

Is there any way to integrate PHP-DI bridge in current skeleton?

**Comment by odan** [comment]
I have already tried to integrate the PHP-DI bridge into this skeleton, but it caused so many strange problems. 
After a lot of troubles I decided to not integrate or use the PHP-DI bridge anymore. 
Of course, you can still integrate it into your own application.

**Comment by ybelenko** [comment]
> I have already tried to integrate the PHP-DI bridge into this skeleton, but it caused so many strange problems. 
> After a lot of troubles I decided to not integrate or use the PHP-DI bridge anymore. 

Then you decided not to submit an issue to PHP-DI bridge about these strange problems. 😁 They might get better with your feedback now. Sad world of opensource...

**Comment by ybelenko** [comment]
I think this issue shouldn't be closed. Just as reminder of a wanted feature for a next major release.

**Comment by odan** [comment]
You should be more careful with your words my friend. I'm working 12h per days and more. I have a family. I maintain and support over 50 open-source repositories in my spare time for free. I'm blogging about open-source projects and I wrote an eBook about Slim. I'm teaching people. I help people in conferences. I help developers worldwide on StackOverFlow, in the Slim Forum, in the Slim Slack channel via email and other channels, almost 7 days a week. I was burnt out already.

If people like you think this is still not enough for the open-source community, then yes, it's a really sad world of open-source. 😢

**Comment by ybelenko** [comment]
@odan Sorry, if it sounded disrespectful to you. 

I'm working 24/7 from 2011. Never been on vacation. Got no family, because want to work all the time.

Submit an issue with a short message doesn't take much of a time. `Submit an issue != maintain a package`.

**Comment by odan** [comment]
> Submit an issue with a short message doesn't take much of a time. Submit an issue != maintain a package.

I don't agree. Submitting short an short issue without detailed explaination, a minimal example and so is not helpful for the maintainers. Submiting a good issue takes time (sometimes hours). When you submit an issue, you also maintain it in a certain way. But anyway, feel free to add PHP-DI Slim Bridge to your project when you need it.
