### ISSUE TITLE
getParsedBody

### ISSUE THREAD

**Issue by ledahu** [odan/slim4-skeleton#31]
Hi

i have a middleware 
`<?php

namespace App\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Slim\Views\Twig;
use Symfony\Component\HttpFoundation\Session\Session;

final class OldInputMiddleware implements MiddlewareInterface
{

    private Twig $view;

    private Session $session;
    /**
     * @param $request
     * @param $response
     * @param $next
     * @return mixed
     */
    public function __construct(Session $session,Twig $view)
    {
        $this->session = $session;
        $this->view= $view;
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {

        $tmp=$request->getParsedBody();
         var_dump($tmp);

        return $handler->handle($request);
    }
}`

when i submit a form POST , the dump is empty , the getMethod is "GET" 

`<?php

use App\Middleware\OldInputMiddleware;
use App\Middleware\SessionMiddleware;
use App\Middleware\UrlGeneratorMiddleware;
use App\Middleware\ValidationErrorsMiddleware;
use Selective\BasePath\BasePathMiddleware;
use Selective\Validation\Middleware\ValidationExceptionMiddleware;
use Slim\App;
use Slim\Csrf\Guard;
use Slim\Middleware\ErrorMiddleware;
use Slim\Views\TwigMiddleware;

return function (App $app) {

   $app->add(ValidationExceptionMiddleware::class);
   $app->add(Guard::class);
    $app->add(UrlGeneratorMiddleware::class);

    $app->addRoutingMiddleware();

    $app->add(TwigMiddleware::class);
    $app->add(OldInputMiddleware::class); // EMPTY getParsedBody
    $app->add(ValidationErrorsMiddleware::class);
    $app->add(SessionMiddleware::class);
    $app->add(BasePathMiddleware::class);
    $app->addBodyParsingMiddleware();
    $app->add(ErrorMiddleware::class);

};`

any idea ?

**Comment by ledahu** [comment]
add: if i add this middleware to the pure skeleton, after a failed login i didnt get the Post Var 
still empty !

**Comment by odan** [comment]
Have you checked the Content-Type?

https://www.slimframework.com/docs/v4/middleware/body-parsing.html#media-type-detection

**Comment by ledahu** [comment]
yes, as you can see, the bodyParsingMiddleware is in the stack

**Comment by odan** [comment]
I have already seen that you have added the BodyParsingMiddleware . That's why my question was if you checked the "Content-Type" inside the request for one of the supported media type.

* application/json
* application/x-www-form-urlencoded
* application/xml
* text/xml

**Comment by ledahu** [comment]
i do not send json. 
I just want that after a post submit , the middleware push the fiels in addGlobals to let it set as default value in twig field is submit raise validation errors 

so, in slim3 , i had a  

`<?php

namespace App\Middleware;

class OldinputMiddleware extends Middleware
{
    /**
     * @param $request
     * @param $response
     * @param $next
     * @return mixed
     */

    public function __invoke($request, $response, $next)
    {
        if(isset($_SESSION['old']))
            $this->container->view->getEnvironment()->addGlobal('old',$_SESSION['old']);

        $_SESSION['old']=$request->getParams();
        $response=$next($request,$response);

        return $response;
    }
}`

now i must set the session in the Action, but in theory i must get the parsedbody 
may it come frome the use of responder->redirect ? 
the point i dont understant is that is i dump $request, i get the pasedbody array in it (protected) 
but $request->getParsedBody is empty 

how to check the content-type by a dump ?

**Comment by odan** [comment]
After a HTTP redirect the HTTP method is `GET` (and not POST anymore), so the submitted form data will always be empty after a redirect. HTTP is designed like this. If you want to keep a state from the last request you have to store it for example in a session. 
As long as your form is in POST mode, you can render the form data directly into template again, whiteout sessions.
A "better" option would be to send only the form data via Ajax to the server for input validation and storage in the database.
Generally I would try to avoid saving form data into a session, but I don't have enough context to give an accurate answer.

**Comment by ledahu** [comment]
It's just to let the user don't have to rewrite if form fail. 
By the way, ok, i understand that redirect is GET.

**Comment by odan** [comment]
Hi @ledahu Could you find a solution?
