### ISSUE TITLE
PHP Session timeout

### ISSUE THREAD

**Issue by nmatias** [odan/slim4-skeleton#32]
How do I expire a PHP session after 30 minutes for example? I try this to add this values in the config/defaults.php but it doesn't work:

// Session
$settings['session'] = [
    'name' => 'webapp',
    'cache_expire' => 0,
    'gc_maxlifetime' => 3600,
    'cookie_lifetime' => 604800
];

Thanks,
Nelson Matias

**Comment by odan** [comment]
According to the [documentation](https://symfony.com/doc/current/components/http_foundation/session_configuration.html#session-cookie-lifetime) the `cookie_lifetime` is in seconds and should be 60 * 30 = 1800 to expire the cookie after 30 minutes. A cookie lifetime of 0 means the cookie expires when the browser is closed.

I would try **exactly** this here first:

```php
// Session
$settings['session'] = [
    'name' => 'webapp',
    'cookie_lifetime' => 1800,
];
```

Don't pass any `gc_*` settings to use the default values of the system. If my example from above is still not working try to configure the [garbage collector](https://symfony.com/doc/current/components/http_foundation/session_configuration.html#configuring-garbage-collection) settings manually. You can play with these settings by passing `gc_probability`, `gc_divisor` and `gc_maxlifetime`. [Read more](https://symfony.com/doc/current/components/http_foundation/session_configuration.html#configuring-garbage-collection)

**Comment by nmatias** [comment]
Thanks Daniel,

Work perfectly. I have already say that but the work and support you give to the community is to be commended.

Thanks a lot!!!
