### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by devtkn** [odan/slim4-skeleton#33]
Hello Odan,

I am new to slim and this skeleton project. I tried to install this skeleton on my MacBook on a local Apache Web Server. Before I installed the skeleton I ensured that I could access php and html files from the server. 

I put my skeleton under a /bp subdir. 

Now, when I enter http://localhost/bp I get the errormessage: "Forbidden" from the server. Where can I start to look what went wrong with my installation?

 Thank you!

**Comment by odan** [comment]
Hi @devtkn You could check the apache error logfile. I think the location depends on the OS version. It should be somewhere located in: 

* `/var/log/apache2/error_log` or 
* `/var/log/apache2/error.log` or
* `/private/var/log/apache2/error_log` or

You could also find the location for 'CustomLog' and 'ErrorLog' in your Apache configuration files, which are under `/etc/apache2/httpd.conf`

**Comment by devtkn** [comment]
Thanks for your hint. I checked those files and changed adjusted the httpd.conf file. No I get the following error-messages from slim, when I enter /localhost/bp:

500 Internal Server Error - Error details: [0] Webpack manifest file not exists. in /Library/WebServer/Documents/bp/templates/home/home.twig on line 4. Backtrace: #0 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Parser.php(182): Fullpipe\TwigWebpackExtension\TokenParser\EntryTokenParserCss->parse(Object(Twig\Token)) #1 /Library/WebServer/Documents/bp/vendor/twig/twig/src/TokenParser/BlockTokenParser.php(45): Twig\Parser->subparse(Array, true) #2 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Parser.php(182): Twig\TokenParser\BlockTokenParser->parse(Object(Twig\Token)) #3 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Parser.php(95): Twig\Parser->subparse(NULL, false) #4 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Environment.php(479): Twig\Parser->parse(Object(Twig\TokenStream)) #5 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Environment.php(507): Twig\Environment->parse(Object(Twig\TokenStream)) #6 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Environment.php(348): Twig\Environment->compileSource(Object(Twig\Source)) #7 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', 'home/home.twig') #8 /Library/WebServer/Documents/bp/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load('home/home.twig') #9 /Library/WebServer/Documents/bp/vendor/slim/twig-view/src/Twig.php(146): Twig\Environment->render('home/home.twig', Array) #10 /Library/WebServer/Documents/bp/vendor/slim/twig-view/src/Twig.php(202): Slim\Views\Twig->fetch('home/home.twig', Array) #11 /Library/WebServer/Documents/bp/src/Responder/Responder.php(69): Slim\Views\Twig->render(Object(Slim\Psr7\Response), 'home/home.twig', Array) #12 /Library/WebServer/Documents/bp/src/Action/Home/HomeAction.php(43): App\Responder\Responder->render(Object(Slim\Psr7\Response), 'home/home.twig', Array) #13 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): App\Action\Home\HomeAction->__invoke(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #14 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #15 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Psr7\Request)) #16 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #17 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #18 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Psr7\Request)) #19 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(66): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request)) #20 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\BodyParsingMiddleware->process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner)) #21 /Library/WebServer/Documents/bp/vendor/selective/validation/src/Middleware/ValidationExceptionMiddleware.php(62): class@anonymous->handle(Object(Slim\Psr7\Request)) #22 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Selective\Validation\Middleware\ValidationExceptionMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #23 /Library/WebServer/Documents/bp/src/Middleware/TranslatorMiddleware.php(80): class@anonymous->handle(Object(Slim\Psr7\Request)) #24 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): App\Middleware\TranslatorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #25 /Library/WebServer/Documents/bp/src/Middleware/SessionMiddleware.php(43): class@anonymous->handle(Object(Slim\Psr7\Request)) #26 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): App\Middleware\SessionMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #27 /Library/WebServer/Documents/bp/src/Middleware/UrlGeneratorMiddleware.php(43): class@anonymous->handle(Object(Slim\Psr7\Request)) #28 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): App\Middleware\UrlGeneratorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #29 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(60): class@anonymous->handle(Object(Slim\Psr7\Request)) #30 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #31 /Library/WebServer/Documents/bp/vendor/slim/twig-view/src/TwigMiddleware.php(125): class@anonymous->handle(Object(Slim\Psr7\Request)) #32 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Slim\Views\TwigMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #33 /Library/WebServer/Documents/bp/vendor/selective/basepath/src/BasePathMiddleware.php(52): class@anonymous->handle(Object(Slim\Psr7\Request)) #34 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Selective\BasePath\BasePathMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #35 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Psr7\Request)) #36 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous)) #37 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request)) #38 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #39 /Library/WebServer/Documents/bp/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request)) #40 /Library/WebServer/Documents/bp/public/index.php(3): Slim\App->run() #41 {main}

**Comment by odan** [comment]
This is because the file `public/assets/manifest.json` doesn't exists.

Have you installed the skeleton according to the  [documentation](https://odan.github.io/slim4-skeleton/setup/composer.html#installation-using-composer) with this command?

```
composer create-project odan/slim4-skeleton my-app
```

If you don't have a `public/assets` directory then run this manually:

```
npm install
```

and

```
npm run build
```

**Comment by devtkn** [comment]
There was no /public/assets folder after the installation. I installed with:

`php composer.phar create-project odan/slim4-skeleton bp`.

Now after `npm install`  and `npm audit fix` i got

`found 19 vulnerabilities (16 low, 2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
thomas@Thomass-MBP bp % npm audit fix
updated 1 package in 9.668s

30 packages are looking for funding

  run `npm fund` for details

fixed 15 of 19 vulnerabilities in 1022 scanned packages
  3 vulnerabilities required manual review and could not be updated
  1 package update for 1 vulnerability involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)`

I  ran `npm audit fix --force` and finally `npm run build`. Now I have the /bp/public/assets with manifest.json.

And now everything works fine. 

Thank you very much for your help!!!

Tom
>
