### ISSUE TITLE
Why is the session started from an Action? Isn't it already started from the SessionMiddleware?

### ISSUE THREAD

**Issue by notflip** [odan/slim4-skeleton#36]
I wonder if you could explain to me what the reason for this line is, in the LoginSubmitAction.php, it starts the session, however I notice it is already started from the SessionMiddleware, which is added to the application's middleware stack.

https://github.com/odan/slim4-skeleton/blob/642f71e8d97067508e18863cdfca4a3d8ae7879f/src/Action/Auth/LoginSubmitAction.php#L88

Thank you!

**Comment by odan** [comment]
Hi @notflip Yes, the session is already started in the SessionMiddleware. 
For security reasons, the Session-ID must be **regenerated after a successful login**. For this reason only the LoginSubmitAction clears and destroys the old session and regenerates the session ID. To set the logged-in user, the new session must be started first using the `start` method.

**Comment by notflip** [comment]
Thanks for getting back, Daniel! I did not know about the need for regenerating session after a login. Is this commonly done? I'm amazed by the ADR way of structuring this repository, it's perfect

**Comment by odan** [comment]
Yes. You should regenerate the session on login, to help defend against session hijacking / [fixation](https://en.wikipedia.org/wiki/Session_fixation) and [login CSRF](http://seclab.stanford.edu/websec/csrf/csrf.pdf).

See [OWASP's recommendation for more](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change).

> The session ID must be renewed or regenerated by the web application after any privilege level change within the associated user session. ...
