### ISSUE TITLE
How to use the /src/Handler/DefaultErrorHandler.php

### ISSUE THREAD

**Issue by notflip** [odan/slim4-skeleton#37]
I'm looking into ways of outputting more information when a 404 happens, I'm using the following code at the moment

```
    $app->addBodyParsingMiddleware();
    $app->addRoutingMiddleware();

    // Error Middleware
    $loggerFactory = $app->getContainer()->get(\App\Factory\LoggerFactory::class);
    $logger = $loggerFactory->addFileHandler('error.log')->createInstance('error');

    $app->addErrorMiddleware(true, true, true, $logger);
```

So I'm wondering, the file in this repository, `src/Handler/DefaultErrorHandler.php`, how can I make sure that this one is used instead of the default in Slim? Thank you!

**Comment by odan** [comment]
You can also find more examples here: https://odan.github.io/2020/05/27/slim4-error-handling.html
