### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by darkalchemy** [odan/slim4-skeleton#4]
Hello,

I am still very new to slim and to your project. I have just created a new test project following the instructions in the documentation. When I get to ``composer migrate`` it errors with this
```
> phinx migrate -c config/phinx.php --ansi
Phinx by CakePHP - https://phinx.org.

using config file ./config/phinx.php

In Driver.php line 92:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE] [-x|--dry-run] [--fake]

Script phinx migrate -c config/phinx.php --ansi handling the migrate event returned with error code 255
```

I guessed that I missed something so I started over and retraced the steps. It errors with the same error, each time.

Could you help me to figure out what I am missing or doing wrong?

Thanks

**Comment by odan** [comment]
Hi @darkalchemy 

The error message indicates that a MySQL connection via socket is tried (which is not supported).

I guess this is just an database connection configuration (maybe in combination with docker) issue. You can try to replace the default database 'host' => 'localhost', with: 'host' => '127.0.0.1'.

**Comment by darkalchemy** [comment]
Thank you for the response. Yes, I am running this in a docker container.
I have added it ``config/env.php`` so it looks like this.
```
$settings['db']['database'] = 'test';
$settings['db']['username'] = 'root';
$settings['db']['password'] = '';
$settings['db']['host'] => '127.0.0.1'
```
and a different error shows now
```
> phinx migrate -c config/phinx.php --ansi
Phinx by CakePHP - https://phinx.org.

using config file ./config/phinx.php
Script phinx migrate -c config/phinx.php --ansi handling the migrate event returned with error code 255
```

I appreciate you taking the time to assist a newbie!

**Comment by odan** [comment]
> handling the migrate event returned with error code 255

The exit code 255 sound like a fatal error in PHP.

I assume the problem can come from multiple sources.

* Check for possible PHP syntax errors
* Check the server error logfiles to get more details.
* Check your directory read/write permissions
* Do you use Postgres?

**Comment by darkalchemy** [comment]
Ah, I think the error is mysql and mysql_native_password. I don't believe php-pdo can use the new secure password.

Thank you for your help and this project.
