### ISSUE TITLE
Real time notification

### ISSUE THREAD

**Issue by nmatias** [odan/slim4-skeleton#43]
Hi,

This is not an issue, but a question. What are the best solution to implement real time notification in a notification bar to integrate in slim4-skeleton. I start to read some information in the web to get a possible solution and i find multiple references to pusher service, but to be honest, I don't want to have dependencies with a pay solution. I also find references for a Ratchet php websocket solution that seems promising. My conclusion for now, is for performance issues, the solution must be a websocket solution.

The purpose here it's for example, someone fill a contact form in the website, and the person that are in the backoffice, receive a notification (a pulsing icon or anything else) stating that there is a new request for information.

Thanks!
Nelson Matias

**Comment by odan** [comment]
Websocket is a different "paradigm" (persistent connection) with different problems like memory management, long-running process, shared state between clients etc. 

Here you can find some interesting solutions:

* Ratchet: https://github.com/shulard/ipc-websocket-sample
* [Artillery](https://artillery.io/): https://github.com/shulard/ipc-websocket-artillery
