### ISSUE TITLE
DataTableRepository fails on DISTINCT

### ISSUE THREAD

**Issue by cirolaferrara** [odan/slim4-skeleton#46]
If _$query_ contains DISTINCT clause, _recordsTotal_ and _recordsFiltered_ displays wrong value.

**Comment by odan** [comment]
What have you tried so far?

**Comment by cirolaferrara** [comment]
Hi @odan.
[This is the database dump](https://pastebin.com/BCYE2DW4)
[This is the method into Repository](https://pastebin.com/UXQidPuW)
[This is the result](https://pastebin.com/2ePZMgc0)
[This is what I think must have](https://pastebin.com/7934MFVC)

**Comment by odan** [comment]
Ok this is a special use case. `DISTINCT` is implemented by `GROUP BY` under the hood.

The SQL of your query looks like this:

```sql
SELECT `people`.* FROM `people_link`
LEFT JOIN `people` `people` ON people_link.id_people = people.id
GROUP BY `people`.`id`
```

So this query would give the same result:

```php
$query = $this->queryFactory->newSelect('people_link');
$query->select(['people.*'])
    ->group('people.id')
    ->leftJoin('people', 'people_link.id_people = people.id');
```

Your requirement is to get count of number of groups. So we need two operations-

* group(inner query)
* count(outer query)

To fix the counter you have to open the class  `DataTableRepository` and then replace this lines:

```php
$countQuery = clone $query;
$countQuery->select(['count' => $countQuery->func()->count('*')], true);
```

with this lines:

```php
$countQuery = $this->queryFactory->newQuery()->from(['sub' => $query]);
$countQuery->select(['count' => $query->func()->count('*')], true);
```

Resulting SQL for the count query:

```sql
SELECT (COUNT(*)) AS `count` FROM (SELECT `people`.* 
FROM `people_link` 
LEFT JOIN `people` `people` ON people_link.id_people = people.id 
GROUP BY `people`.`id` ) `sub`
```

This fix should give you the correct count value:

![image](https://user-images.githubusercontent.com/781074/103312903-b91b9900-4a1e-11eb-90a7-222d334c7ac7.png)

**Comment by cirolaferrara** [comment]
Perfect! Thank you 👍
