### ISSUE TITLE
Slim 4 Skeleton docker-compose missing

### ISSUE THREAD

**Issue by thedarkknight197** [odan/slim4-skeleton#47]
Hi i am following your wiki on: https://odan.github.io/slim4-skeleton/setup/docker.html
but after i have created my application with: 

`composer create-project odan/slim4-skeleton my-app`

the file docker-compose.yml will not create, and i can't run my docker container.

Anyone can help me? 

Thank you

**Comment by odan** [comment]
The docker-composer.yml file is part of the skeleton. See here:
https://github.com/odan/slim4-skeleton/blob/master/docker-compose.yml

**Comment by thedarkknight197** [comment]
![Schermata 2021-01-07 alle 13 38 01](https://user-images.githubusercontent.com/37689698/103893440-9c055b00-50ed-11eb-8766-56ec69f81f09.png)
Cloning your repo


Trying adding docker-compose.yml and Dockerfile from your repo to my project that i have created before i have this error: 
![Schermata 2021-01-07 alle 13 45 12](https://user-images.githubusercontent.com/37689698/103894055-a1af7080-50ee-11eb-83da-8132dc2783c5.png)

**Comment by thedarkknight197** [comment]
I have update my env file with

`// Database
$settings['db']['database'] = 'test';
$settings['db']['username'] = 'root';
$settings['db']['password'] = 'root';
$settings['db']['host'] = 'testslim_db_1';`

Now i Recive:
![Schermata 2021-01-07 alle 13 55 04](https://user-images.githubusercontent.com/37689698/103895044-0e773a80-50f0-11eb-90c8-32210b16d9d2.png)
![Schermata 2021-01-07 alle 13 55 37](https://user-images.githubusercontent.com/37689698/103895047-10d99480-50f0-11eb-957b-c569af625897.png)

**Comment by odan** [comment]
> Notice: Undefined index index column_name in DataTableRepository.php line 220

This PHP notice is not related to the docker container itself. It looks like the `column_name` is not defined.
Please try to clone the latest version of the repo.

**Comment by thedarkknight197** [comment]
Mh I think that I miss to import the db. I have to do migration or you have an import mysql-dump?

**Comment by thedarkknight197** [comment]
I use Laravel, to do migration I need to run:

`php artisan migrate`

Exist for Slim a similar running command? I only create my db without table. but it call the db: test, I don't know if is this the problem. Now I am at Home, tomorrow at work I see the project

**Comment by odan** [comment]
Slim is a micro-framework and provides only routing and dispatching functionality. 
This skeleton provides a phinx to migrate the table structure, e.g. `composer migrations:migrate`

**Comment by thedarkknight197** [comment]
On your docker launched at /var/www/html

`composer migrations:migrate

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "migrations" namespace.    
                                                                  `

**Comment by thedarkknight197** [comment]
if i move in resources:

`cd resources
# ls 
docker	locale	migrations  seeds
# composer migrations:migrate
No composer.json in current directory, do you want to use the one at /var/www/html? [Y,n]? y

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "migrations" namespace.    
                                                                  

`

**Comment by odan** [comment]
All commands must be started from the project-root directory.
Composer is usually only installed on the development machine but not on the production server.

For development (only)
`composer migrations:migrate`

For production:

> If Composer is not installed on the target server, the following command can be used:
> $ vendor/bin/phinx migrate -c config/phinx.php

Please read the documentation of this skeleton-project first.

https://odan.github.io/slim4-skeleton/database.html#update-schema
