### ISSUE TITLE
Ant build fails

### ISSUE THREAD

**Issue by cirolaferrara** [odan/slim4-skeleton#48]
Hi @odan. Check this please

`composer create-project odan/slim4-skeleton my-app`
`composer build`

```
C:\my-app>composer build
> ant build
Buildfile: C:\my-app\build.xml

build:
      [get] Getting: https://getcomposer.org/composer.phar
      [get] To: C:\my-app\build\composer.phar
     [exec] fatal: not a git repository (or any of the parent directories): .git

BUILD FAILED
C:\my-app\build.xml:73: exec returned: 128

Total time: 8 seconds
Script ant build handling the build event returned with error code 1
```

**Comment by odan** [comment]
> fatal: not a git repository (or any of the parent directories): .git

Your project is not versioned. So the build script cannot fetch the latest version from git.

**Comment by cirolaferrara** [comment]
[doc](https://odan.github.io/slim4-skeleton/deployment.html) sould be update 👍
