### ISSUE TITLE
ORM for database

### ISSUE THREAD

**Issue by francescopasin** [odan/slim4-skeleton#52]
Hello. Your work is great and I used it in a quite big project, finding it very well organized and structured.
Working with it I struggled sometimes with the repository concept. There is a lot of code replication between different repositiories and lot of times I needed to go and change code in different files. Also CakePhp is not well documented (in the way you use it).
May I suggest to use ORM for database communication? It could be more practical and reduce code boilerplate.
I found this library http://propelorm.org/ that I think is awesome for different reasons:

- Incredibly well documented
- Easy to use
- Migration and schema dump is included (probably better than using a different service for the migration)

Well this is just an opinion :) And I wanted to share my feedback about this project after using it.

One last thing: it would be nice to include in this repo some example of different scenarios and use cases (for example I used a react frontend and the backend only for rest api). It could be useful if someone needs to understand the "correct" way of using this (I can try to share some example and collaborate in this project if you want).

Nice work!

**Comment by odan** [comment]
Hi @francescopasin Thanks for your feedback.

By purpose this skeleton project works with Repositories to abstract the data access logic and to make the core application independent of any implementation under the hood. Well, this is "just" a skeleton and no "framework". You can clone it to modify it as you want. You can also add any ORM or QueryBuilder you want to use within the Repositories. Feel free :-)

The latest version of this Skeleton was refactored for API's only. So you may test it and give me a feedback.
