### ISSUE TITLE
odan/phinx-migrations-generator -> PHP 8.0.2

### ISSUE THREAD

**Issue by preetamforu** [odan/slim4-skeleton#53]
When trying to install latest slim4-skeleton with php 8.0.2 getting following error for dependent composer package. I am also using composer 2.0 to manually install all composer dependencies.

 Problem 1
    - odan/phinx-migrations-generator[5.0.0, ..., 5.3.2] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires odan/phinx-migrations-generator ^5 -> satisfiable by odan/phinx-migrations-generator[5.0.0, ..., 5.3.2].

**Comment by odan** [comment]
This `odan/phinx-migrations-generator` package has been updated for PHP 8 now. Please try it again.
