### ISSUE TITLE
NoSQL database testing

### ISSUE THREAD

**Issue by KipchirchirIan** [odan/slim4-skeleton#56]
I don't know if my question is going to make sense but I am using NoSQL(Firebase). How would you handle testing in this case?? I would also appreciate if you would share some ideas on how to use/integrate NoSQL databases with this project. Thank you!

**Comment by odan** [comment]
In principle, this should work like with normal databases, except that you don't have to provide a fixed schema.

* Reset database
* If necessary: Create fixtures
* Perform test
* Check result in the database
