### ISSUE TITLE
Offset not working in UserFinderRepository.php

### ISSUE THREAD

**Issue by ziauddin** [odan/slim4-skeleton#59]
$offset = min($params['offset'] ?? 0, 0);
I think this line return always 0 If I set positive integer value in the $param['offset']. So I fixing it in my repository function and just pointed in here as a reminder its not working :-).

I really like this repository and its really helpful to understood slim and use it for my current api development project.
Really appreciate.
Ziauddin

**Comment by odan** [comment]
Good catch. It should be `$offset = max($params['offset'] ?? 0, 0);`.
Would you like to create a PR?

**Comment by ziauddin** [comment]
I would love to and I wish to contribute more on this project.

**Comment by odan** [comment]
Fixed #60
