### ISSUE TITLE
TwigMiddleware is not called when processing DefaultErrorHandler

### ISSUE THREAD

**Issue by tobiascapin** [odan/slim4-skeleton#6]
I'm trying to customize the error.twig templat and its twigextensions is not working (for example base_path() ). While debugging I have found that the TwigMiddleware is not loaded when the twig render is called by the DefaultErrorHandler.

**Comment by tobiascapin** [comment]
I think the solution is to move down the twigMiddleware addition in middleware.php. If it is before the `addRoutingMiddleware()` the notfound error will not handled with twig extensions.

**Comment by odan** [comment]
That's a good question. I'll look into it.

**Comment by odan** [comment]
Yes, the TwigMiddleware should be added before the RoutingMiddleware to ensure that `base_path' and other Twig helper functions work as expected.

```php
$app->addRoutingMiddleware();
$app->add(TwigMiddleware::class);
```

Thanks for the hint.
