### ISSUE TITLE
Twig assets 

### ISSUE THREAD

**Issue by 262926** [odan/slim4-skeleton#7]
I did followed your tutorial **twig-webpack-extension-setup** with this skeleton which getting error 404. Do you have any idea what cause the problem?

![image](https://user-images.githubusercontent.com/45273745/80081450-3ec37c80-8553-11ea-862c-8576d03a151b.png)

**Comment by odan** [comment]
I'm not sure what you have tried, but try this:

* Run: `npx webpack --mode=development` or just `npx webpack` to build the assets
* Then check if the files exists in the `public/assets/` directory
* If you run your site / app in a sub-directory, make sure you set the correct base href of the html document, e.g.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- other stuff -->
    <base href="{{ base_path() }}"/>
    <!-- other stuff -->
```

* Show me the F12 developer toolbar response.

**Comment by 262926** [comment]
Just creating own simple cms to learn.
I already did mentioned things. Console return 404 errors.
![image](https://user-images.githubusercontent.com/45273745/80087742-d3ca7380-855b-11ea-9eec-84bbed66d6bc.png)

![image](https://user-images.githubusercontent.com/45273745/80087988-302d9300-855c-11ea-8dd8-3d8a439977bd.png)

![image](https://user-images.githubusercontent.com/45273745/80088158-69660300-855c-11ea-80e6-64136392ec64.png)

**Comment by odan** [comment]
Looks good, so far. Try to find the "correct" url for the js/css assets manually.

**Comment by 262926** [comment]
Actually same working on Hosting server but in the localhost. Any idea for it.?

**Comment by odan** [comment]
Sounds like an typical basePath issue if you run Slim in an sub-directory (applies for most development environments). Please give me more details (error message & code, screenshot, directory, etc...).

**Comment by 262926** [comment]
Running directory is c/wamp/www/dts(simple cms). I used your skeleton nothing else. I added some screenshot here. please let me know if you need anything else. Thank you.

**Container:**
![image](https://user-images.githubusercontent.com/45273745/80150080-01dda100-85b8-11ea-819b-64126a4cb837.png)
![image](https://user-images.githubusercontent.com/45273745/80150125-1a4dbb80-85b8-11ea-92db-f1e45625ac9a.png)

**Middleware**
![image](https://user-images.githubusercontent.com/45273745/80151150-dfe51e00-85b9-11ea-9a39-e1210c023d19.png)


**Error:**
![image](https://user-images.githubusercontent.com/45273745/80150872-6f3e0180-85b9-11ea-91a4-7558f38f9f14.png)

**Composer.json**
![image](https://user-images.githubusercontent.com/45273745/80151066-b6c48d80-85b9-11ea-8665-afebd123ac0b.png)

**Comment by odan** [comment]
Your app is running in a sub-directory (under c/wamp/www/dts). So the BasePathMiddleware should set Slims basePath to `/dts` automatically for you.

What is the output of the Twig helper function `base_path()` ?
in your layout/layout.wig file here:
```php
 <base href="{{ base_path() }}/"/>
```

On your localhost the output should be: `<base href="dts/"/>` 
On your prod server the output should be: `<base href="/"/>`

**Comment by dunkoh** [comment]
Is your host root pointed to the public directory inside dts?

**Comment by 262926** [comment]
> What is the output of the Twig helper function `base_path()` ?

@odan Return `<base href="/"/>` - where do i change that?

**Comment by 262926** [comment]
> Is your host root pointed to the public directory inside dts?

i think yes. `C:\wamp\www\dts>php -S localhost:8080 -t public public/index.php`

**Comment by odan** [comment]
Good hint from @dunkoh. I thought you are using apache. If you use the PHPs internal webserver, then you may try this command: 

`cd c:\wamp\www\dts`
`composer start`

The same command without composer:

`cd c:\wamp\www\dts`
`php -S localhost:8080 -t public`

Then navigate to: `http://localhost:8080/`

The base href should then look like this: `<base href="/"/>`

**Comment by 262926** [comment]
@odan Which is works cool!. Thank you.
