### ISSUE TITLE
I need tips on the ADR pattern for programming best practices

### ISSUE THREAD

**Issue by esallum-iluminare** [odan/slim4-skeleton#70]
Hi Odan, I want to thank you immensely for this SLIM 4 skeleton that you provided to the community. However, I have a beginner's doubt:

By the ADR development pattern, let's assume I have a domain called Categories and another one called Subcategories with their respective Actions (following your SLIM 4 skeleton pattern). The Categories action returns the categories and the Subcategories action returns the subcategories for their respective routes.

However, I need a route that returns the subcategories with categories Following good programming practices, can I create an Action SubcategoriesWithCategorie (without any domain) and through this Action access the Categories domain and the Subcategories domain?

**Comment by odan** [comment]
Hi @esallum-iluminare 

The fundamental idea is to build the Application (and the API) around the higher-level **use cases** and not around the (lower-level) database tables. So please don't just build CRUD API for each table. Build API for the concrete problems you are trying to solve. Focusing on capabilities is the key. I already mentioned this in my [Slim 4 Tutorial](https://odan.github.io/2019/11/05/slim4-tutorial.html#domain)

The most detailed answer to this question and other best practices can be found in my [Slim 4 eBook](https://odan.github.io/donate.html). 
Chapter: Clean Architecture and ADR

You also find good information in the [documentation](https://odan.github.io/slim4-skeleton/architecture.html) of this Slim skeleton project.
There is a good video on Youtube that explains the concept very well: [The Entity Service Antipattern](https://www.youtube.com/watch?v=2gOOstEI4vU&lc=)

**Comment by esallum-iluminare** [comment]
Thanks for the clarification. I will develop thinking about the routes and not the database CRUD.

In my specific case, my SubcategoriesWithCategorie action doesn't have any domain, because it uses the Categories domain and the Subcategories domain to return.

In my project it is necessary for me to have a route that returns the Categories, another that returns the Subcategories and another that returns both together. In this case, then my question is: due to good programming practices, in this case, an Action may not have a specific domain, and access two different domains?

**Comment by odan** [comment]
I don't know your exact requirements, so I try to answer it more general.

In general, I would try to split all these different use cases into specific, services. So for each endpoint (URL, route) there should be only one use case specific service class. If you have a piece of common logic, split this logic into a separate class and share it with the other classes. Take a look at the context and find out what this specific class does (SRP), then it should be clear how to name it. If you have a shared logic, try to find this shared logic and extract it into another class.

When you focus on the capabilities, you see that every use case is different.

Example:

* Use case 1 returns enity1.field1, enity1.field2
* Use case 2 returns enity1.field1, enity1.field3 and enity2.field5, enity2.field6, enity2.field7.
* Use case 3 returns enity3.field9, enity3.field4, enity3.field5 from and enity2.field1, enity2.field3.
* Use case 4 returns enity1.field1 and a custom formatted field from enity2.field3
* and so on...

So when you build an endpoint that needs data from multiple sources you also build
a "use case specific query", that selects only the tables, fields you really need. 
The relation between the tables can be defined using a JOIN statement.

I have already answered similar questions here. I hope it helps. By eBooks contains more details.


* https://github.com/odan/slim4-tutorial/issues/32#issuecomment-836753344
* https://github.com/odan/slim4-tutorial/issues/35
* https://github.com/odan/slim4-tutorial/issues/29

**Comment by esallum-iluminare** [comment]
Thanks for the answer.

In my case, my domain in question is as follows:
https://pastebin.com/De24gQ4v .

My routes:
//Subcategories w/ Category
$app->get('/subcategories-with-category/{id_subcategory}', \App\Action\SubCategoryCategory\SubCategoryCategoryReadAction::class);
$app->options('/subcategories-with-category/{id_subcategory}', PreflightAction::class);
 
As I understand it, the way I did it is wrong. The correct way is to create a Domain (with its respective Repository and Data) that contains a Service titled SubCategoryCategoryReader 

Detail: I'm planning to buy your book :)

**Comment by odan** [comment]
> The correct way is to create a Domain (with its respective Repository and Data) that contains a Service titled SubCategoryCategoryReader

Yes, correct. Just invoke one Service (not more) that handles the task (business logic) with the corresponding repository(s) that retrieves only the required data for that specific use case.

**Comment by borgogelli** [comment]
Hi everyone,
I need to convert an old controller class which has 10 methods which are associated to 10 routes to the ADR pattern. 
Should I have to write 10 Action classes or there is an more concise alternative solution ?
Regards
