### ISSUE TITLE
composer migrate not found

### ISSUE THREAD

**Issue by nesjett** [odan/slim4-skeleton#75]
The documentation states to execute "composer migration:migrate" but It seems not working anymore:

![image](https://user-images.githubusercontent.com/7051231/125661780-5fccb76f-d848-4892-aed9-3bbd07e5af88.png)

![image](https://user-images.githubusercontent.com/7051231/125661831-2a1172b8-be61-4727-b15a-cd6fb742476b.png)

It does work if you execute "composer phoenix migrate" tho.

Latest version of this repo, cloned today with the command "composer create-project odan/slim4-skeleton my-app"

- Greetings

**Comment by odan** [comment]
Thank you, the documentation has been fixed.
