### ISSUE TITLE
curious on your reasons for switching from phinx to phoenix?

### ISSUE THREAD

**Issue by dunkoh** [odan/slim4-skeleton#76]
@odan  We've been using Phinx for db migrations/changes since it was part of your skeleton previously. I'm curious on your reasoning for switching to Phoenix, so that I might know if it will be worth the change for us?

**Comment by odan** [comment]
The main reasons for Phoenix are that it is a more lightweight, brings fewer dependencies and also has an [integrated diff command](https://github.com/lulco/phoenix/blob/master/docs/commands/diff_command.md).  Phoenix is also not so opinionated about the default table structure.

Phinx is still perfectly fine. If you are already using Phinx, then definitely keep using it.

**Comment by ziauddin** [comment]
I also love phoenix for its simplicity and light weight. I use different migration library is different project. but after using phoenix I believe it's easy to use and adoption with it is very fast.

**Comment by dunkoh** [comment]
Thank you!
