### ISSUE TITLE
Error: Parameter #3 $level of class Monolog\Handler\RotatingFileHandler

### ISSUE THREAD

**Issue by ll-ld** [odan/slim4-skeleton#78]
![image](https://user-images.githubusercontent.com/86779336/130197228-3c251178-141d-4175-b717-a33de5273702.png)

Hello, I get this error after a fresh installation/repo creation of slim4-skeleton and cant find any help how to solve this. 
pls help me out with some advice, thank you in advance.

**Comment by odan** [comment]
Thanks for reposting this error message. This is a known issue, see here:

* https://github.com/odan/slim4-skeleton/runs/3070370446

It appears to be a bug in the DocBlocks of Monolog. See here:

* https://github.com/Seldaek/monolog/blob/2.3.2/src/Monolog/Handler/RotatingFileHandler.php#L46-L52
* https://github.com/Seldaek/monolog/blob/2.3.2/src/Monolog/Handler/StreamHandler.php#L43-L50

The DocBlock does not match with the actual constructor parameters. 

When I fix the DocBlock in RotatingFileHandler and StreamHandler manually, the phpstan errors are gone.

```php
/**
 * @param string $filename
 * @param int $maxFiles
 * @param int $level
 * @param bool $bubble
 * @param int|null $filePermission
 * @param bool $useLocking
 */
public function __construct(string $filename, int $maxFiles = 0, $level = Logger::DEBUG, bool $bubble = true, ?int $filePermission = null, bool $useLocking = false)
```

```php
/**
 * @param resource|string $stream If a missing path can't be created, an UnexpectedValueException will be thrown on first write
 * @param int $level
 * @param bool $bubble Try to lock log file before doing any writes
 * @param int|null $filePermission Optional file permissions (default (0644) are only for owner read/write)
 * @param bool $useLocking
 *
 * @throws \InvalidArgumentException If stream is not a resource or string
 */
public function __construct($stream, $level = Logger::DEBUG, bool $bubble = true, ?int $filePermission = null, bool $useLocking = false)

```

The best way to fix this would be to create a PR in the monolog repository.

**Comment by odan** [comment]
As a quick fix you could add `/** @phpstan-ignore-next-line */` to ignore this phpstan error.

See here: https://github.com/odan/slim4-skeleton/commit/cfce80023b2c9805e8c5bf2bc5bf2b39cbb9a9c1
