### ISSUE TITLE
Handling relationships within the skeleton structure

### ISSUE THREAD

**Issue by curVV** [odan/slim4-skeleton#79]
Any pointers on how to start looking at handling database relationships within this structure of factories/repositories/data/services etc?

Anything I think of involves either rewriting just about everything and/or making too many queries instead of one join query or feels like I'm trying to reinvent an ORM. I might be missing the obvious since I'm still having a hard time wrapping my head around all the fractions of logic in different places.

**Comment by odan** [comment]
Hi @curVV 

Yes, you don't need to reinvent an ORM.

The [documentation](https://odan.github.io/slim4-skeleton/database.html) of this project contains more details.
This page explains more about [Repositories](https://odan.github.io/slim4-skeleton/domain.html#repositories).

In my [blog](https://odan.github.io/) and this [Slim 4 eBook](https://ko-fi.com/s/5f182b4b22) you can take a deeper look at these topics.  Example: [Slim 4 - Cake QueryBuilder](https://odan.github.io/2019/12/03/slim4-cakephp-query-builder.html)

And last but not least: If you have a specific question, you can file an issue here or consult me directly.

**Comment by curVV** [comment]
Hi, sorry I wasn't being clear. I've read the documentation and I understand how to use joins using the query builder. But it is not clear to me how to implement these relationships into the structure set out in the skeleton.

Say for instance I have a table called articles that contain articles that belong to users. If I want to implement this relationship in the current structure of the skeleton, how would you go about doing this? The `UserRepository->getUserById()` method returns a `UserData` object. Should I add a `UserData->articles()` method that would call something like `ArticlesRepository->getArticlesbyUserId($this->id)` so I could do `$user->articles()`? But that just means a separate query, no joins performed. That does not seem efficient to me. Trying to think of other ways...

**Comment by odan** [comment]
In my [eBook](https://ko-fi.com/s/5f182b4b22) I explain the [Clean Architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) much more in detail. 

The key point is to "think" and build software in [use cases](https://proandroiddev.com/why-you-need-use-cases-interactors-142e8a6fe576). So it's a complete  "mind shift", if you will.

Here is a collection of very similar questions where you can also find some answers. I hope it helps.

* https://github.com/odan/slim4-tutorial/issues/33
* https://github.com/odan/slim4-tutorial/issues/32
* https://github.com/odan/slim4-tutorial/issues/29
* https://github.com/odan/slim4-tutorial/issues/37
* https://github.com/odan/slim4-skeleton/issues/63
* [Highly COHESIVE Software Design to tame Complexity](https://www.youtube.com/watch?v=r0-GC3Y_OME)
* [The ORM / Active Record Anti-pattern](https://www.mehdi-khalili.com/orm-anti-patterns-part-1-active-record)

**Comment by curVV** [comment]
Makes sense, thank you.
