### ISSUE TITLE
Use for REST API only.

### ISSUE THREAD

**Issue by KipchirchirIan** [odan/slim4-skeleton#8]
Sorry in advance if this question is not meant to be here. How would I use this skeleton to develop a REST API only while also ensuring a front-end dev can easily integrate their UI with this?I would like to avoid including npm/webpack related stuff, github workflow e.t.c. I'm learning how to use Slim framework for creating REST API and this is very new to me.

**Comment by odan** [comment]
Hi @KipchirchirIan It should be quite easy to trim down the project for a RESTful API.

But it would be easier if you start with this more minimal Slim4-Skeleton for API's:

* https://github.com/odan/slim4-tutorial

If you want to trim down this Slim4-Skeleton, then try this:

* Download the latest version
* Delete all frontend config files, e.g. jest.config.js, package.json, package-lock.json, tsconfig.json, webpack.config.js
* Delete the `templates/` directory
* Remove the frontent dependencies: 

```
composer remove fullpipe/twig-webpack-extension
composer remove slim/twig-view
composer remove symfony/http-foundation
composer remove symfony/serializer
composer remove symfony/translation
composer remove symfony/twig-bridge
```

Remove the translator function in composer.json

```
 "files": [
            "src/Utility/translate.php"
        ]
```

In `src/Responder/Responder.php` remove the `render() method and all Twig dependencies.

Delete the files:

```
src/Console/TwigCompilerCommand.php
src/Repository/DataTableRepository.php

**Comment by KipchirchirIan** [comment]
Thank you! This helped a lot.
