### ISSUE TITLE
create-project is not downloading some files

### ISSUE THREAD

**Issue by gilberto-olivas** [odan/slim4-skeleton#81]
When I create project using the 0.19.3 version some files are missing
- build.xml
- .editorconfig
- sonarcloud
- etc

I create project with same composer version only change the package version to 0.19.2 and it comes with all the files

![Screenshot 2021-10-11 195239](https://user-images.githubusercontent.com/56657777/136883203-f0ae9556-835e-4680-ab88-10980f8e5f43.png)

**Comment by odan** [comment]
The change from #80 has been reverted, because this is a skeleton-project that needs this files.
