### ISSUE TITLE
Undefined function 'uuid_create' in LoggerFactory

### ISSUE THREAD

**Issue by DigiLive** [odan/slim4-skeleton#85]
https://github.com/odan/slim4-skeleton/blob/ad0e03eefd92bae1ded2535083456cf95893d61c/src/Factory/LoggerFactory.php#L54

Where is function `uuid_create()` defined?

**Comment by odan** [comment]
It's part of the `symfony/polyfill-uuid` package.

**Comment by DigiLive** [comment]
Ah... I didn't think of the packages.
My apologies.
