### ISSUE TITLE
Twig + Mailer Integration Issue 

### ISSUE THREAD

**Issue by fvtorres** [odan/slim4-skeleton#9]
Hey @odan

I went though your Tutorial, the Twig implementation and the Mailer Implementation.
Would like to thank you for these awesome tutorials.

So good so far, but when I tried to use Twig inside emails, it simply doenst work. I was following the official documentation in Mailer, but I get an error:
Type: Symfony\Component\Mime\Exception\LogicException
Code: 0
Message: A message must have a text or an HTML part or attachments.
File: /vendor/symfony/mime/Email.php
Line: 405

I found a reference in this github:
symfony/symfony#35990

If this is easy to solve, I guess it would be nice to be in your tutorials

**Comment by fvtorres** [comment]
Here is the Official Documentation I mentioned 

https://symfony.com/doc/current/mailer.html#twig-html-css

**Comment by fvtorres** [comment]
Wow!

That worked like a charm!!

Thank you very much!! Have been 3 days trying to do that.

Now I will integrate:
cssinliner-extra
league/commonmark

**Comment by fvtorres** [comment]
Success! Here is the code I used in container.php: 

`use Twig\Extra\CssInliner\CssInlinerExtension;
use Twig\Extra\Inky\InkyExtension;
use Twig\Extra\Markdown\MarkdownExtension;
use Twig\Extra\Markdown\DefaultMarkdown;
use Twig\Extra\Markdown\MarkdownRuntime;
use Twig\RuntimeLoader\RuntimeLoaderInterface;

  // Twig templates
    Twig::class => function (ContainerInterface $container) {
        $config = $container->get(Configuration::class);
        $settings = $config->getArray('twig');

        $options = $settings['options'];
        $options['cache'] = $options['cache_enabled'] ? $options['cache_path'] : false;

        $twig = Twig::create($settings['paths'], $options);

        $twig->addRuntimeLoader(new class implements RuntimeLoaderInterface {
            public function load($class) {
                if (MarkdownRuntime::class === $class) {
                    return new MarkdownRuntime(new DefaultMarkdown());
                }
            }
        });

        // Add more extension here
        $twig->addExtension(new CssInlinerExtension());
        $twig->addExtension(new InkyExtension());
        $twig->addExtension(new MarkdownExtension());

        return $twig;
    },`

**Comment by odan** [comment]
Thanks for sharing.

**Comment by fvtorres** [comment]
The cssinliner-extra and twig/inky-extra are working by using that approach!

But the Markdown is being called as a filter but not producing any result. Maybe because it isn't linking to the league/commonmark, but I receive no errors at all,

Will keep trying here. If I discover will post here

Thanks!

**Comment by fvtorres** [comment]
Well, could't get the Markdown to work. It apparently is running (or at least some part of it), but nothing happpens.

I'm wondering if the code is in the right place: `    $twig->addRuntimeLoader(new class implements RuntimeLoaderInterface {
        public function load($class) {
            if (MarkdownRuntime::class === $class) {
                return new MarkdownRuntime(new DefaultMarkdown());
            }
        }
    });`

If you have some more time, could I ask for some more help?

Thanks!

**Comment by odan** [comment]
Yes, it looks correct. 

https://github.com/odan/slim4-skeleton/issues/12#issuecomment-623713126
