### ISSUE TITLE
404 in  /docs/configuration.md 

### ISSUE THREAD

**Issue by tertek** [odan/slim4-skeleton#90]
In file:
https://github.com/odan/slim4-skeleton/blob/master/docs/configuration.md

at line: 82

`[Slim 4 - Laminas Config](https://odan.github.io/2021/03/21/slim4-laminas-config.html)`

has a 404

**Comment by tertek** [comment]
Hi there,

I have additional improvements for the docs. Would you like me to add them each as new issue or would you prefer me to open a PR? In case of PR I cannot always know what the desired improvement would be (such as above) so I would comment out and add notes where needed.

**Comment by odan** [comment]
Thanks for reporting the invalid link. It has been removed.
You can create a PR in a dimension that makes sense to you.
