### ISSUE TITLE
How to handle query error ?

### ISSUE THREAD

**Issue by pazDontExist** [odan/slim4-skeleton#91]
Hi, thanks for the amazing work, this skeleton and your book are really something.
Just one question...as the title say...how do you handle query insert/general error ?

**Comment by odan** [comment]
I handle this by catching the exception. For example, when I start a database transaction, I roll it back if an exception occurs.

See here: [Transaction](https://odan.github.io/2019/12/03/slim4-cakephp-query-builder.html#transactions)

To catch and render all other kind of (database and application) errors,  I configured the Slim ErrorMiddleware to use a custom `DefaultErrorHandler` that renders the Exception into a proper HTTP JSON response. 

https://github.com/odan/slim4-skeleton/blob/master/src/Handler/DefaultErrorHandler.php
https://github.com/odan/sample-tracking/blob/master/config/container.php#L136
https://github.com/odan/slim4-skeleton/blob/master/config/middleware.php

**Comment by pazDontExist** [comment]
yes im using the transactions. 

and the try/catch too. 

but in this case the insert doesnt trigger the exception but yet its not done. 

```php
try {
          $id_dog = $this->queryFactory->newInsert('dogs', $row)->execute()->lastInsertId();
          // THIS GET CALLED
          if (!$id_dogs) {
              $this->transaction->rollback();
              return ['status' => 'error', 'message' => Definition::ERR_ADD_DOG];
          }

      } catch (\Exception $e){
         // THIS NOT
          echo $e->getMessage();
      }
```

how can i "debug" this and understand why it fails ?

**Comment by odan** [comment]
It looks like the `lastInsertId` returns a new ID. So the query might work. 

Make sure to [enable exception](https://github.com/odan/slim4-skeleton/blob/master/config/defaults.php#L60) for the database connection.

```php
PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
```

You also don't need to check for `!$id_dogs` then because if something was wrong, the Exception should be thrown anyway.

Also make sure to commit the transaction. Otherwise the insert command changes nothing and the transaction will be reverted at the end.

Example:

```php
use Exception;
// ...

try {
    $this->queryFactory->newInsert('dogs', $row)->execute();
    $this->transaction->commit(); // <--- this is needed
} catch (Exception $e){
    $this->transaction->rollback();
    // Optional log error here
    // ...
}
```

**Comment by pazDontExist** [comment]
thank you so much

**Comment by pazDontExist** [comment]
Thank you so much !

Il Mar 10 Mag 2022, 22:42 Daniel Opitz ***@***.***> ha
scritto:
